### ISSUE TITLE
Set up Laravel Homestead on Mac

### ISSUE THREAD

**Issue by keer2345** [keer2345/laravel-learning#1]
# Step 1 
**Install [Vagrant](https://www.vagrantup.com/downloads.html)**
```
brew cask install vagrant
```

# Step 2
**Install [Virtualbox](https://www.virtualbox.org/wiki/Downloads)**
```
brew cask install virtualbox
```

# Step 3
**Add Homestead to Vagrant Box**

Open terminal and run the following command:
```
vagrant box add laravel/homestead
```

You may get a response like this:

```
This box can work with multiple providers! ...
1) hyperv
2) parallels
3) virtualbox
4) vmware_desktop
```
We are using VirtualBox, so enter the option 3. This will take quite a while. It may even take up to 2 hours.

```
> vagrant box list
laravel/homestead (virtualbox, 10.1.1)
```

# Step 4
**Start installing Homestead** 
```
mkdir -p workspace/laravel
git clone https://github.com/laravel/homestead.git
```
```
> cd homestead
> bash init.sh
Homestead initialized!
```

# Step 5
**Create Keys**

Open the file named `Homestead.yaml` under your **homestead** folder.

You will see these lines in the file:
```
authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa
```

If you haven't the two file, you should create it with command:
```
ssh-keygen -t rsa -C "you@homestead"
```

You will get a response like this:
```
Your identification has been saved in /Users/technofreek/.ssh/id_rsa.
Your public key has been saved in /Users/technofreek/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxx you@homestead
The key's randomart image is:
+---[RSA 2048]----+
[image]
+----[SHA256]-----+
```

# Step 6
**Configure Homestead**

Now navigate back one step so that you are inside `~/workspace/laravel` folder.

```
cd ~/workspace/laravel
mkdir code
```

Modify `~/workspace/laravel/homestead/Homestead.yaml`:
```
folders:
    - map: ~/workspace/laravel/code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      # to: /home/vagrant/code/public
      to: ~/workspace/laravel/code/myproject1/public

databases:
  # - homestead
    - myproject1
```

# Step 7
**Start Homestead machine**

```
cd ~/workspace/laravel/homestead
```
Make the vagrant machine up and running:
```
vagrant up
```

If you make any changes to the *Homestead.yaml* file, you can restart the server by calling these commands
```
vagrant halt
```
and then
```
vagrant up
```

Alternatively, this one command also suffices to reprovision your server:
```
vagrant provision
```
or
```
vagrant up --provision
```

Now run the following command to ssh into the machine. This uses the key that we generated to login into the machine.
```
vagrant ssh
```
This should bring up the command line.
```
vagrant@homestead:~$

vagrant@homestead:~$ ls
code
```
# Step 8
**Install Laravel in Homestead**
```
cd code
composer global require laravel/installer
```

# Step 9
**Create first project** in `vagrant@homestead:~/code$`:
```
laravel new myproject1
```

# Step 10
**Configure the project**

**Firstly**, Add the names of the new project **site** and **database** to the respective places.
```
sites:
    - map: myproject1.test
    to: /home/vagrant/code/myproject1/public
databases:
    - myproject1
```

**Secondly**, go to *myproject1/.env* file, in the *code/myproject1* folder, and change the following values to set the database name and set the default username and password used by homestead.
```
DB_DATABASE=myproject1
DB_USERNAME=homestead
DB_PASSWORD=secret
```

# Step 11
**Map the hosts file**

The domain that we have set which is ‘myproject.test’. In order to be able to open this in our browser we need to add it to the system hosts file.
```
sudo vi /etc/hosts
```

Add follow to last line:
```
127.0.0.1       myproject1.test
```

# Step 12
**Run**

Open http://myproject1.test:8000/ ,You should see a basic LARAVEL website.

# Step 13
**Setting up multiple projects/sites**

First, (same as step 9) let us create the second project from laravel machine. Log in to it and navigate to code folder and simply create the new project. We’ll name it as proj2.
```
vagrant ssh
cd code
laravel new proj2
```

**Second**, for configuring the new project, (same as step 10) go to Homestead.yaml file and make new entries for sites and databases, and give the names.
```
sites:
    - map: myproject1.test
    to: /home/vagrant/code/myproject1/public
    - map: proj2.demo
    to: /home/vagrant/code/proj2/public
databases:
    - myproject1
    - proj2
```

And, go to proj2/.env file, which is inside code/proj2 folder and change the following values:
```
DB_DATABASE=proj2
DB_USERNAME=homestead
DB_PASSWORD=secret
```
Third, (same as in step 11), open a new terminal window, edit hosts file, and add an entry for the new site.
```
127.0.0.1       myproject1.test
127.0.0.1       proj2.demo
```

That’s all. Open your browser and try both URLs, they should work fine and the basic laravel site page should appear.
```
http://proj2.demo:8000/
http://myproject1.test:8000/
```
But these look the same for now. Let us change the title for both websites.

Go to the code folder of the first project, in my case its Documents/laravel/code/myproject1.

Open the file
```
myproject1/resources/views/welcome_blade.php
```
Change the heading text in the body
```
<div class="title m-b-md">
My first project
</div>
```
Save and close. Run the reset provision command
```
vagrant up --provision
```
And refresh the websites. You should be able to see different headings.
